### ISSUE TITLE
ERROR: Package pdftex.def Error: File `./images/graph_binary4.pdf' not found: using draft setting.

### ISSUE THREAD

**Issue by djpeebles** [simbrain/NeuralNetworksCogSciBook#1]
Compiling the book, I receive the error above and the graph is missing from p.42 of the book.

**Comment by jyoshimi** [comment]
Thanks for bringing this to my attention! The .gitignore was too aggressive in ignoring pdfs.  It should be fixed. Please confirm.

**Comment by djpeebles** [comment]
Yes, that works fine now - thanks!
